export const INIT_SUBSPACE = "INIT_SUBSPACE";
export const DEPLOY_CONTRACT = "DEPLOY_CONTRACT";
export const SUBSPACE_READY = "SUBSPACE_READY";
export const MY_ACTION = "MY_ACTION";
export const DUMMY_TRANSACTION = "DUMMY_TRANSACTION";

